### Obter todos os checkups
GET http://localhost:8080/api/v1/checkups
Accept: application/json

###

### Criar um novo checkup
POST http://localhost:8080/api/v1/checkups
Content-Type: application/json
Accept: application/json

{
  "dataHora": "2023-10-01T14:30:00",
  "local": "Museu Histórico",
  "usuarioIdentifier": "teste@exemplo.com"
}

###

### Atualizar um checkup existente
PUT http://localhost:8080/api/v1/checkups/1
Content-Type: application/json
Accept: application/json

{
  "dataHora": "2023-10-02T15:00:00",
  "local": "Museu de Arte Moderna",
  "usuario": {
    "id": 1
  }
}

###

### Excluir um checkup por ID
DELETE http://localhost:8080/api/v1/checkups/1
Accept: application/json
